version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: alertifyprojectdb
    volumes:
      - mongo:/data/db

  app:
    build:
      context: .
    container_name: alertify
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    env_file:
      - .env

volumes:
  mongo: